spring:
  application:
    name: dish-roles-service
  datasource:
    url: jdbc:postgresql://localhost:5432/dish
    username: postgres
    password: postgres
    hikari:
      schema: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  servlet:
    context-path: /dish/roles-service/
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /admin/actuator
feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

service:
  property:
    name: aws
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/